### ISSUE TITLE
Add padding between cells

### ISSUE THREAD

**Issue by reckbo** [andmarti1424/sc-im#36] opened 2015-10-21 00:59 UTC
I can't find a way to pad cells so that there is a space between adjacent cell values.  Is there a way to do this?

**Comment by andmarti1424** [comment] 2015-10-21 17:23
Pad of cells is not supported right now. May be we can add that in the future. Does sc have this?
Note that if you need to give cells a space, you might achieve what you want changing column width..

**Comment by reckbo** [comment] 2015-10-21 21:13
Great, thank you.

**Comment by riX2000** [comment] 2016-01-30 03:04
In addition to padding it would also be nice to have an easy way to set every other row and column to have different alternating colors. (Especially if support for 256 colors are added).

**Comment by andmarti1424** [comment] 2016-02-17 12:38
Is padding supported in SC?

**Comment by andmarti1424** [comment] 2016-02-18 12:39
You know you can change columns width,  right?

**Comment by riX2000** [comment] 2016-02-18 13:36
Yes. But the problem is that right now a cell with right adjusted content next to a cell with left adjusted content looks like one string, it's hard to see where the next cell starts.
This could be fixed with padding or colors.

**Comment by andmarti1424** [comment] 2016-02-18 13:45
Yes. You have this problem..
Changing colors work. But padding will be better.

2016-02-18 10:36 GMT-03:00 riX2000 <notifications@github.com>:

**Comment by andmarti1424** [comment] 2016-03-23 14:39
I am working on padding... Should it be applied to en entire column or individual cells?

**Comment by riX2000** [comment] 2016-03-23 14:52
Preferrably both :)
If I have to choose I would go with column, it might look weird if you just have padding in one single cell somewhere.

**Comment by andmarti1424** [comment] 2016-03-23 22:07
Please try latest dev branch commit. Now you can add padding to columns typing:

:pad 2
or any number of chars of space you want. (see doc in help).

You can also use visual mode to select columns and then type the above command.

**Comment by riX2000** [comment] 2016-03-24 16:13
Very nice, working perfectly. :)

**Closed** 2016-03-24 20:33 UTC
Labels: feature request, fixed / done

**Comment by tasnuva1** [comment] 2023-09-01 15:44
Is there any way You can add padding or space to a cell or row in y axis position (top to bottom). Like this:

![pic-selected-230901-2152-58](https://github.com/andmarti1424/sc-im/assets/62549329/0125afec-ee0f-45bd-af6f-58fa0df373b1)

Is there any way of replicating this look? It would be really helpful.

**Comment by andmarti1424** [comment] 2023-09-01 15:50
you can increase row height with `fj` and then you can enter `\n\nsome text..` as cell text content.

**Comment by tasnuva1** [comment] 2024-01-03 10:07
> you can increase row height with `fj` and then you can enter `\n\nsome text..` as cell text content.

Thanks for telling.
