### ISSUE TITLE
Cellcolors saved incorrectly

### ISSUE THREAD

**Issue by riX2000** [andmarti1424/sc-im#42] opened 2016-01-30 02:07 UTC
Cellcolors are saved to file without the first letter of the color.
Example from saved file:
cellcolor A0 "fg=REEN bg=HITE"

edit:
removing lines 286 and 293 in file.c marked with "FIXME THIS" solves the problem, but I don't understand what those lines are supposed to do.

**Comment by andmarti1424** [comment] 2016-01-30 12:42
Hello. What version are you using?
I have noticed this strange behaviour before.
In some computers it gets saved well, but in others it gets saved with something like "fg=@GREEN bg=@WHITE".
And I still dont know why that happens!!
I did that awful hack in those two lines to quickly resolve that. So Its strange in your get saved without the '@' and without the first letter as well!!
May be other can help and see what I am not able to see here..

**Comment by andmarti1424** [comment] 2016-02-01 23:48
Anyother had this issue? Please report.

**Comment by riX2000** [comment] 2016-02-02 11:36
Version 0.2.1 from the AUR.
I tried to figure out why too, but for me the code is very hard to read.
I was going to do some testing again, but now I get segfaults when trying to save..

**Comment by andmarti1424** [comment] 2016-02-02 13:27
Please try latest commit in dev branch!
I believe lines 286 and 293 with the following content:
_if (line[0] == '@') del_char(line, 0);_
does not exists in release v0.2.

**Comment by riX2000** [comment] 2016-02-02 16:51
Ok, yes i removed them myself and recompiled, which solved the issue. I just wanted to be sure it didn't break any other functionality.

On February 2, 2016 2:27:28 PM GMT+01:00, "Andrés M." <notifications@github.com> wrote:
>Please try latest commit in dev branch!
>I believe lines 286 and 293 with the following content:
>_if (line[0] == '@') del_char(line, 0);_
>does not exists in release v0.2.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/andmarti1424/sc-im/issues/42#issuecomment-178574541

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by andmarti1424** [comment] 2016-02-15 14:58
Do you still have this issue?
Could you please download latest dev branch version, build it without changing any line, and report back?

Thanks.

**Comment by riX2000** [comment] 2016-02-16 11:27
I still have the same problem I wrote about in my email to you, I'm getting a segfault when trying to save, so I cannot test this issue.
I tried the version in the AUR again, wich has the color issue, but does not segfault, so I don't think the segfault are because something in my system changed.

**Comment by andmarti1424** [comment] 2016-02-17 15:19
This is fixed. I leave this open just to discover why in some computers the decompilation adds a @ and in others dont.

**Comment by laanwj** [comment] 2016-04-07 18:02
I'm not able to reproduce this with any combination of compiler flags. The `@` is always added at the beginning.

The only thing I can think of is that:

    for (s = "@err"; (line[linelim++] = *s++); );

Doesn't evaluate on the same way in every C compiler. It is a strange use of a for loop, to make an assignment in the condition clause of the for loop, but I don't see why it would be undefined behavior. The two post-increments increment different variables.

@riX2000 If you still have access to the system that produced this output could you try saving the following as `outloop.c`:
```
#include <stdio.h>

int main()
{
    int linelim = 0;
    char line[100];
    char *s;
    for (s = "@black"; (line[linelim++] = *s++); );
    printf("%s\n", line);
}
```
Then do `gcc outloop.c -O2 -o outloop` and see what the output of `./outloop ` is?
This would help isolate it at least.

**Comment by riX2000** [comment] 2016-04-07 18:04
Output is
@black

**Comment by laanwj** [comment] 2016-04-07 18:23
Thanks. THat seems to disprove my hypothesis that the problem is that for statement.

**Comment by andmarti1424** [comment] 2016-04-07 21:10
@riX2000, if you delete those "if (line[0] == '@') del_char(line, 0);" lines, do you still have the problem?

Do colors get saved like this:
cellcolor A0 "fg=REEN bg=HITE"??

**Comment by riX2000** [comment] 2016-04-07 22:00
I tried with the latest commit, both commenting those lines and leaving them makes the colors get saved correctly.
However, using the newest version from the arch AUR makes them being saved incorrectly. (Version 0.2.1)

**Comment by andmarti1424** [comment] 2016-04-08 00:20
Thanks for your work, @laanwj.
If you comment those "if (line[0] == '@') del_char(line, 0);" lines.
How cellcolor lines are saved for you??

It should save like this:
cellcolor A0 "fg=GREEN bg=WHITE"
and not like this:
cellcolor A0 "fg=@GREEN bg=@WHITE"
nor this, obviously:
cellcolor A0 "fg=REEN bg=HITE"

**Comment by laanwj** [comment] 2016-04-08 06:27
Commenting them out makes no difference to me:
```
cellcolor A1 "fg=RED bg=GREEN"
```
However, when I comment out the `uppercase` too I get:
```
cellcolor A1 "fg=@red bg=@green"
```
So it's `uppercase()` that removes the `@`. That's an interesting discovery. Looking at the uppercase function I'm pretty sure I found the problem:
```c++
void uppercase(char * sPtr) {
    while(*sPtr != '\0') {
         *sPtr++ = toupper(*sPtr);  // UNDEFINED BEHAVIOR: sPtr is used twice, once in a increment - sequence depends on C compiler
    }
}
```

**Comment by laanwj** [comment] 2016-04-08 06:35
See #67

**Comment by andmarti1424** [comment] 2016-04-08 12:16
Great work!! Thank you very much for your help.!

**Comment by andmarti1424** [comment] 2016-04-08 12:55
Merged pull request! I close this issue!

**Closed by andmarti1424** 2016-04-08 12:55 UTC
Labels: fixed / done, help wanted
