### ISSUE TITLE
OS X color support lost on 0.4.0

### ISSUE THREAD

**Issue by stsg** [andmarti1424/sc-im#107] opened 2016-12-08 12:12 UTC
Building on macOS 10.12.1 with latest homebrew ncurses, but color support is lost in 0.4.0.
Running in latest iTerm2 with TERM=xterm-256color
Any ideas?

**Comment by andmarti1424** [comment] 2016-12-08 12:21
No colors at all? Please check USECOLORS in your Makefile.

**Comment by stsg** [comment] 2016-12-08 12:32
No color at all. Bright only.
Makefile diff:

```
< prefix=/usr
> prefix=/usr/local

< LINUX := -DLINUX
> LINUX :=

< MACOSX :=
> MACOSX := -DMACOSX
```

**Comment by stsg** [comment] 2016-12-08 12:33
USECOLORS := -DUSECOLORS

**Comment by stsg** [comment] 2016-12-08 12:49
version 0.3.0

![030](https://cloud.githubusercontent.com/assets/476151/21010542/a46db86e-bd5d-11e6-9d29-2e6219dfe8c4.png)

version 0.4.0

![040](https://cloud.githubusercontent.com/assets/476151/21010546/a9e84ed0-bd5d-11e6-87a1-7597af926843.png)

**Comment by andmarti1424** [comment] 2016-12-12 12:39
Do you use the same terminal?

**Comment by stsg** [comment] 2016-12-12 12:47
Yes, of course.

```
> echo $TERM
xterm-256color
```

**Comment by andmarti1424** [comment] 2016-12-12 12:48
I meant your terminal emulator. Not your TERM env. variable.

**Comment by stsg** [comment] 2016-12-12 12:49
Yes, shure.
ITerm 2 Build 3.0.13

**Comment by stsg** [comment] 2016-12-12 12:57
version 0.3.0
```
> otool -L /usr/local/bin/scim
/usr/local/bin/scim:
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
        /usr/local/opt/ncurses/lib/libncursesw.6.dylib (compatibility version 6.0.0, current version 6.0.0)
```
version 0.4.0
```
> otool -L ./scim
./scim:
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
        /usr/local/opt/ncurses/lib/libncursesw.6.dylib (compatibility version 6.0.0, current version 6.0.0)

```

**Comment by andmarti1424** [comment] 2016-12-12 14:58
I really do not know what the problem could be. Will wait for other OS X users to get their feedback and see if this happen to them as well.

**Comment by andmarti1424** [comment] 2016-12-12 15:46
Does colors in headings show correctly?

**Comment by stsg** [comment] 2016-12-12 16:05
No! No colorant all.
0.3.0
<img width="265" alt="header_030" src="https://cloud.githubusercontent.com/assets/476151/21106138/ef4bbbcc-c09d-11e6-9aa2-765b28df6e45.png">
0.4.0
<img width="306" alt="header_040" src="https://cloud.githubusercontent.com/assets/476151/21106143/f5e84b58-c09d-11e6-8a47-ceb12d589963.png">

**Comment by andmarti1424** [comment] 2016-12-12 16:11
Could you please attach the entire Makefile?

**Comment by stsg** [comment] 2016-12-12 16:17
[Makefile-0.3.0.txt](https://github.com/andmarti1424/sc-im/files/646513/Makefile-0.3.0.txt)

[Makefile-0.4.0.txt](https://github.com/andmarti1424/sc-im/files/646515/Makefile-0.4.0.txt)

**Comment by andmarti1424** [comment] 2016-12-13 00:07
I have installed sc-im v4.0 today in a OS X Sierra virtual machine running in Virtual Box:
It was a fresh OS X install and these were my steps to get sc-im running:

1. ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
2. brew install homebrew/dupes/ncurses
3. git clone https://github.com/andmarti1424/sc-im
4. edit Makefile (just these lines:)
< LINUX := -DLINUX
> LINUX :=
< MACOSX :=
> MACOSX := -DMACOSX
5. brew link - - force ncurses
6. make

and after finished building, I run sc-im and see colors without issue!

**Comment by stsg** [comment] 2016-12-13 06:48
I have reinstalled ncurses:
```
brew uninstall ncurses
brew install homebrew/dupes/ncurses
brew link --force ncurses
```
I then downloaded v 3.0 from https://github.com/andmarti1424/sc-im/archive/v0.3.0.tar.gz
When building, I get following error:

`./macros.h:48:10: fatal error: 'ncursesw/curses.h' file not found`

I changed Makefile in following way:
```
diff Makefile.orig Makefile

37,38c37,38
< LINUX := -DLINUX
< #LINUX :=
---
> #LINUX := -DLINUX
> LINUX :=
49,50c49,50
< #MACOSX := -DMACOSX
< MACOSX :=
---
> MACOSX := -DMACOSX
> #MACOSX :=
137c137
< CFLAGS := $(LINUX) $(FREEBSD) $(NETBSD) $(MACOSX) -O2 -Wall -pipe -g -I/usr/include/libxml2
---
> CFLAGS := $(LINUX) $(FREEBSD) $(NETBSD) $(MACOSX) -O2 -Wall -pipe -g -I/usr/include/libxml2 $(shell pkg-config --cflags ncursesw)
144c144
< LDLIBS := -lm -lncursesw
---
> LDLIBS := -lm $(shell pkg-config --libs ncursesw)
```
Running v3.0 and it has color support.

I then cloned v4.0:

`git clone https://github.com/andmarti1424/sc-im`

changed Makefile:

```
diff Makefile.orig Makefile

37,38c37,38
< LINUX := -DLINUX
< #LINUX :=
---
> #LINUX := -DLINUX
> LINUX :=
49,50c49,50
< #MACOSX := -DMACOSX
< MACOSX :=
---
> MACOSX := -DMACOSX
> #MACOSX :=
```
building and running, v4.0 has no colors!

Once again, I changed Makefile:

```
diff Makefile.orig Makefile

37,38c37,38
< LINUX := -DLINUX
< #LINUX :=
---
> #LINUX := -DLINUX
> LINUX :=
49,50c49,50
< #MACOSX := -DMACOSX
< MACOSX :=
---
> MACOSX := -DMACOSX
> #MACOSX :=
137c137
< CFLAGS := $(LINUX) $(FREEBSD) $(NETBSD) $(MACOSX) -O2 -Wall -pipe -g -I/usr/include/libxml2 $(shell pkg-config --cflags ncursesw)
---
> CFLAGS := $(LINUX) $(FREEBSD) $(NETBSD) $(MACOSX) -O2 -Wall -pipe -g -I/usr/include/libxml2
142c142
< LDLIBS := -lm $(shell pkg-config --libs ncursesw)
---
> LDLIBS := -lm -lncursesw -L/usr/local/Cellar/ncurses/6.0_2/lib

```
Building:

```
make clean
make
```

And now v4.0 has color support!

pkg-config output:

```
pkg-config --cflags ncursesw
-D_DARWIN_C_SOURCE -I/usr/local/Cellar/ncurses/6.0_2/include -I/usr/local/Cellar/ncurses/6.0_2/include/ncursesw

pkg-config --libs ncursesw
-L/usr/local/Cellar/ncurses/6.0_2/lib -lncursesw
```

**Comment by andmarti1424** [comment] 2016-12-13 15:58
This is definitely a building/linking to ncurses problem.
I will close this, since I cannot reproduce it and since it works in a fresh OSX install.
Will link this to the WIKI though.

**Closed by andmarti1424** 2016-12-13 15:58 UTC
Labels: help wanted

**Comment by andmarti1424** [comment] 2016-12-13 16:00
Thanks again.
